import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { logo } from "@/assets";
import { env } from "@/env/client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next JS, boilerplate",
  icons: {
    icon: logo.src,
    apple: logo.src,
  },
  alternates: {
    canonical: env.NEXT_PUBLIC_ROOT_URL,
  },
  openGraph: {
    type: "website",
    locale: "en",
    url: env.NEXT_PUBLIC_ROOT_URL,
    title: "Create Next App",
    description: "Generated by create next app",
    siteName: "Create Next App",
    images: [
      {
        url: `${env.NEXT_PUBLIC_ROOT_URL}/logo.ico`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Create Next App",
    description: "Generated by create next app",
    images: `${env.NEXT_PUBLIC_ROOT_URL}/logo.ico`,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
