const TITLE = "Create Next App";
const TITLE_SHORT = "CNA";
const TITLE_TEMPLATE = `%s - ${TITLE_SHORT}`;
const DESCRIPTION = "Generated by create next app";
const KEYWORDS = "Next JS, boilerplate";

import logo from "#/logo.ico";

export { TITLE, TITLE_SHORT, TITLE_TEMPLATE, DESCRIPTION, KEYWORDS, logo };
