const TITLE = "Create Next App";
const TITLE_SHORT = "CNA";
const TITLE_TEMPLATE = `%s - ${TITLE_SHORT}`;
const DESCRIPTION = "Generated by create next app";
const KEYWORDS = "Next JS, boilerplate";

import icoLogo from "#/logo.ico";
import imgLogo from "#/logo.png";
import imgHomePageScreenshot from "#/home-page-screenshot.png";
import imgMyPageScreenshot from "#/my-page-screenshot.png";

export {
  TITLE,
  TITLE_SHORT,
  TITLE_TEMPLATE,
  DESCRIPTION,
  KEYWORDS,
  icoLogo,
  imgLogo,
  imgHomePageScreenshot,
  imgMyPageScreenshot,
};
